export const initialStateDefault = {
    data: [] ,
    getData : null,
    status_code : "",
    network_status :  {
        refresh:"" , 
        userinfo: "" , 
        get: "",
        // get_: "",
        getDetail: "",
        getAll: "",
        getAllDetail: "",
        post: "",
        delete: "",
        gets: "",
        getsTrue: "",
        getAllPGUsers: "",
        getAllChildGroups: "",
      },
      error : {
        get: null,
        getDetail: null,
        getAll: null,
        getAllDetail: null,
        post: null,
        delete: null,
        gets: null,
        getsTrue: null,
        getAllPGUsers: null,
        getAllChildGroups: null,
      }
}
